# Generated by Selenium IDE
from audioop import tomono

import pytest
import time
import json
import time
from idlelib.autocomplete import ID_CHARS
from os import times
from telnetlib import XAUTH

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDefaultSuite():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_untitled(self):

        #for login page responsive
        self.driver.get("https://nm-vs.openmentor.net/")
        self.driver.set_window_size(400, 670)
        time.sleep(1)
        self.driver.set_window_size(800, 670)
        time.sleep(1)
        self.driver.set_window_size(1000,670)
        time.sleep(1)
        self.driver.set_window_size(1300,670)
        time.sleep(1)
        print('case 1 passed')

        #for login page functionality

             # invalid login
        self.driver.find_element(By.ID, "mat-input-0").send_keys("luffy@vidyashakti.com")
        time.sleep(1)
        self.driver.find_element(By.ID, "mat-input-1").send_keys("MonkeyDluffy")
        time.sleep(1)
        self.driver.find_element(By.XPATH, "//span[text()='Login']").click()
        time.sleep(3)
        print('case 2 passed')

              #Reset functionality
        self.driver.find_element(By.XPATH, "//span[text()='Reset']").click()
        time.sleep(3)
        print('Case 3 passed')

            #valid login
        self.driver.find_element(By.ID, "mat-input-0").send_keys("sysadmin@vidhyashakti.com")
        time.sleep(1)
        self.driver.find_element(By.ID, "mat-input-1").send_keys("Welcome@12")
        time.sleep(1)
        self.driver.find_element(By.XPATH, "//span[text()='Login']").click()
        time.sleep(5)
        print('case 4 passed')

        #home page responsive
        self.driver.set_window_size(400, 670)
        time.sleep(1)
        self.driver.set_window_size(800, 500)
        time.sleep(1)
        self.driver.set_window_size(1000,670)
        time.sleep(1)
        self.driver.set_window_size(1300,670)
        time.sleep(1)
        print('case 5 passed')

        #User section

            #users button functionality
        self.driver.find_element(By.CSS_SELECTOR, "mat-card.mat-mdc-card mdc-card cards,mat-card-content.mat-mdc-card-content").click()
        time.sleep(3)
        print('Case 6 passed')

            #user session responsive
        self.driver.set_window_size(400, 670)
        time.sleep(1)
        self.driver.set_window_size(800, 500)
        time.sleep(1)
        self.driver.set_window_size(1000, 670)
        time.sleep(1)
        self.driver.set_window_size(1300, 670)
        time.sleep(1)
        print('case 7 passed')

           #add button functionality
        self.driver.find_element(By.XPATH, "//mat-icon[text()='add']").click()
        time.sleep(3)
        print('case 8 passed')

          #add user details responsive
        self.driver.set_window_size(400, 670)
        time.sleep(1)
        self.driver.set_window_size(800, 500)
        time.sleep(1)
        self.driver.set_window_size(1000, 670)
        time.sleep(1)
        self.driver.set_window_size(1300, 670)
        time.sleep(1)
        print('case 9 passed')

           #adding existing user
        self.driver.find_element(By.ID, "username").send_keys("monkeydluffy@gmail.com")
        time.sleep(1)
        self.driver.find_element(By.ID, "name").send_keys("Monkey D.Luffy")
        time.sleep(1)
        self.driver.find_element(By.ID, "mat-select-value-3").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "mat-option-4").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//span[text()='Add User']").click()
        time.sleep(3)
        print('case 10 passed')

           #reset button functionality
        self.driver.find_element(By.XPATH, "//span[text()='Reset']").click()
        time.sleep(3)
        print('case 11 passed')

           #Adding new user
        self.driver.find_element(By.ID, "username").send_keys("zorothekingofhell@gmail.com")
        time.sleep(1)
        self.driver.find_element(By.ID, "name").send_keys("Roronoa Zoro")
        time.sleep(1)
        self.driver.find_element(By.ID, "mat-select-value-3").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "mat-option-3").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//span[text()='Add User']").click()
        time.sleep(3)
        print('case 12 passed')


           #Adding new user only with special char
        self.driver.find_element(By.XPATH, "//mat-icon[text()='add']").click()
        time.sleep(3)
        self.driver.find_element(By.ID, "username").send_keys("specialcharacter@gmail.com")
        time.sleep(1)
        self.driver.find_element(By.ID, "name").send_keys("@#@#$@#@#")
        time.sleep(1)
        self.driver.find_element(By.XPATH, "/html[1]/body[1]/div[2]/div[2]/div[1]/mat-dialog-container[1]/div[1]/div[1]/app-add-user-details[1]/mat-dialog-content[1]/mat-card[1]/mat-card-content[1]/form[1]/div[1]/mat-form-field[3]/div[1]/div[1]/div[2]").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/mat-option[1]").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//span[text()='Add User']").click()
        time.sleep(3)
        print('case 12 passed')

           #close button functionality
        self.driver.find_element(By.XPATH, "//mat-icon[text()='add']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//mat-icon[text()='cancel']").click()
        time.sleep(3)
        print('case 13 passed')

           #back to home functionality
        self.driver.find_element(By.XPATH, "//mat-icon[text()='arrow_back_ios']").click()
        time.sleep(3)
        print("case 14 passed")

        #programmes button functionality
        self.driver.find_element(By.XPATH, "/html[1]/body[1]/app-root[1]/app-side-nav[1]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/app-home[1]/div[1]/div[1]/mat-card[2]/mat-card-content[1]").click()
        time.sleep(3)
        print("case 15 passed")

        #Programmes session

             # Programme session responsive
        self.driver.set_window_size(400, 670)
        time.sleep(1)
        self.driver.set_window_size(800, 500)
        time.sleep(1)
        self.driver.set_window_size(1000, 670)
        time.sleep(1)
        self.driver.set_window_size(1300, 670)
        time.sleep(1)
        print("case 16 passed")

            #add button functionality
        self.driver.find_element(By.XPATH, "//mat-icon[text()='add']").click()
        time.sleep(3)
        print("case 17 passed")

           #Add programme details responsive
        self.driver.set_window_size(400, 670)
        time.sleep(1)
        self.driver.set_window_size(800, 500)
        time.sleep(1)
        self.driver.set_window_size(1000, 670)
        time.sleep(1)
        self.driver.set_window_size(1300, 670)
        time.sleep(1)
        print("case 18 passed")

           #reset button functionality in add programme details
        self.driver.find_element(By.ID, "programme_name").send_keys("Data Analyst")
        time.sleep(1)
        self.driver.find_element(By.ID, "mat-select-value-3").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "mat-option-3").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, "//span[text()='Reset']").click()
        time.sleep(1)
        print("case 19 passed")

           #Add Programme
        self.driver.find_element(By.ID, "programme_name").send_keys("Data Analyst")
        time.sleep(1)
        self.driver.find_element(By.ID, "mat-select-value-3").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "mat-option-3").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, "//span[text()='Add Programme']").click()
        time.sleep(3)
        print("case 20 passed")





        #logout functionality
        self.driver.find_element(By.XPATH, "//span[normalize-space()='Logout']").click()
        time.sleep(5)
        print('case 21 passed')







