# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://nm-vs.openmentor.net/")
    self.driver.set_window_size(516, 672)
    self.driver.find_element(By.ID, "mat-input-0").send_keys("sysadmin@vidhyashakti.com")
    self.driver.find_element(By.ID, "mat-input-1").send_keys("Welcome@12")
    element = self.driver.find_element(By.CSS_SELECTOR, ".mat-accent > .mat-mdc-button-touch-target")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".mat-accent > .mdc-button__label").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".mat-mdc-list-item:nth-child(2) > .mdc-list-item__content div")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".mat-mdc-list-item:nth-child(2) > .mdc-list-item__content div").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".mdc-button:nth-child(5) > .mat-mdc-button-touch-target")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".mdc-button:nth-child(6) > .mdc-button__label")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".cdk-focused > .mdc-button__label").click()
    self.driver.find_element(By.ID, "mat-input-2").send_keys("sysadmin@vidhyashakti.com")
    self.driver.find_element(By.ID, "mat-input-3").send_keys("Welcome@12")
    self.driver.find_element(By.CSS_SELECTOR, ".mat-accent > .mdc-button__label").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".mdc-icon-button:nth-child(7) > .mat-mdc-button-touch-target")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".mdc-button:nth-child(6) > .mat-mdc-button-touch-target")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".cdk-focused > .mdc-button__label").click()
    self.driver.find_element(By.ID, "mat-input-4").send_keys("sysadmin@vidhyashakti.com")
    self.driver.find_element(By.ID, "mat-input-5").send_keys("Welcome@12")
  
